//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

// TODO: Abstract the Fabric submodules
//  Move the Fabric submodules into a common module
subprojects {
	dependencies {
		// Fabric Loader
		modCompileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
	}
}
