//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

archivesBaseName = "drp"
group = 'com.sigmundgranaas'
version = project.version

dependencies {
	// Fabric (use modImplementation for proper remapping in dev environment)
	modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
	modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")

	// Testing
	testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
	testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")
	testImplementation("net.fabricmc:fabric-loader-junit:${project.loader_version}")
}

loom {
	runs {
		testServer {
			server()
			name = "Test Server"
			source sourceSets.test
		}
		gameTest {
			inherit testServer
			name "Game Test"
			vmArg "-Dfabric-api.gametest"
			runDir "build/gameTest"
		}
		testClient {
			client()
			name = "Test Client"
			vmArg "-Dfabric-api.gametest.structures.output-dir=${file("src/test/resources/data/forgero-drp/gametest/structures")}"
			source sourceSets.test
		}
	}
}

sourceSets {
	test {
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath
	}
}

test {
	useJUnitPlatform()
	maxParallelForks = 16
	testLogging.events("failed")
	testLogging.info.events = ["failed", "skipped"]
}
