//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	implementation(project(":forgero-core-2"))
	implementation(project(path: ":fabric:modules:common", configuration: 'namedElements'))
	implementation(project(path: ":fabric:modules:loader", configuration: 'namedElements'))

	runtimeOnly(project(path: ":fabric:modules:armor",  configuration: 'namedElements'))
	runtimeOnly(project(path: ":fabric:modules:tools",  configuration: 'namedElements'))
	runtimeOnly(project(path: ":fabric:modules:render",  configuration: 'namedElements'))
	runtimeOnly(project(path: ":fabric:modules:properties",  configuration: 'namedElements'))

	// Resources
	runtimeOnly(project(path: ":content:minecraft-vanilla-materials"))
	runtimeOnly(project(path: ":content:forgero-tools"))
	runtimeOnly(project(path: ":content:forgero-armor"))
	runtimeOnly(project(path: ":content:minecraft-tools"))

	// Fabric
	modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
	modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")

	// Testing
	testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
	testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")
	testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

sourceSets {
	test {
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath
	}
}

test {
	useJUnitPlatform()
	maxParallelForks = 32
	testLogging.events("failed")
	testLogging.info.events = ["failed", "skipped"]
}
