//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck

tasks.register('updateDevResources') {
	description = "Updates the build resources for all runtime content packs for hot-reloading."
	group = "Forgero Development"

	// Define which project's 'processResources' task we want to run
	def contentProjects = [
		project(":content:forgero-materials"),
		project(":content:forgero-base"),
		project(":content:forgero-armor"),
		project(":content:minecraft-tools")
	]

	contentProjects.each { proj ->
		dependsOn proj.tasks.named("processResources")
	}

	doFirst {
		logger.lifecycle("Updating development resources for hot-reloading...")
		logger.lifecycle("Will run 'processResources' for:")
		contentProjects.each { proj ->
			logger.lifecycle("- ${proj.path}")
		}
	}

	doLast {
		logger.lifecycle("All content pack resources are now updated in their build/resources directories.")
	}
}

subprojects {
	dependencies {
		implementation(project(":${rootProject.mod_id}-core-legacy-read-only"))
		testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
	}

	processResources {
		inputs.property "version", rootProject.version

		filesMatching("fabric.mod.json") {
			expand "version": rootProject.version
		}
	}

	test {
		useJUnitPlatform()
	}
}
