//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	api(project(":forgero-core-2"))
	api(project(path: ":fabric:modules:common", configuration: 'namedElements'))

	// Fabric
	modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
	modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")
}
