//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	implementation(project(":modules:core"))
	implementation(project(path: ":modules:mc:common", configuration: 'namedElements'))
	implementation(project(path: ":modules:mc:loader", configuration: 'namedElements'))

	// Fabric API
	modCompileOnly("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")

	// Mixins
	modCompileOnly("net.fabricmc:fabric-loader:${project.loader_version}")

	modImplementation("maven.modrinth:arrp:${project.advanced_runtime_resource_pack_version}")
}

loom {
	accessWidenerPath = file("src/main/resources/render.accesswidener")
}
