//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	implementation(project(":modules:core"))
	implementation(project(":modules:model"))
	implementation(project(path: ":modules:mc:common", configuration: 'namedElements'))
	implementation(project(path: ":modules:mc:loader", configuration: 'namedElements'))

	// Fabric API
	modCompileOnly("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")

	// Mixins
	modCompileOnly("net.fabricmc:fabric-loader:${project.loader_version}")

	// Dynamic Resource Pack module
	implementation(project(path: ":mods:drp", configuration: 'namedElements'))

	// Test dependencies
	testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
	testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")
	testImplementation(project(":modules:core:test-common"))
}

test {
	useJUnitPlatform()
	testLogging.events("failed")
	testLogging.info.events = ["failed", "skipped"]
}

loom {
	accessWidenerPath = file("src/main/resources/render.accesswidener")
}
