//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	api(project(":modules:core"))
	api(project(path: ":modules:mc:common", configuration: 'namedElements'))

	// Fabric
	modCompileOnly("net.fabricmc:fabric-loader:${project.loader_version}")
	modCompileOnly("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")
}
