//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	implementation(project(":modules:core"))

	// Fabric API
	modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")
}

loom {
	accessWidenerPath = file("src/main/resources/common.accesswidener")
}
