# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/sigmundgranaas/forgero/issues"

license = "MIT"
[[mods]]
modId = "minecraft_common"
displayName = "Forgero for Forge common library"
loaderVersion = "[43,)"
version = "0.10.2"
# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
#optional
# A list of mods - how many allowed here is determined by the individual mod loader

description = '''
Tool creation and crafting mod for Minecraft
'''

# An (optional) dependency for your mod. Though technically not required,
# it's always helpful to add these to stop your mod from loading when something is missing
# rather than erroring out later
[[dependencies.minecraft_common]]
modId = "forge"
mandatory = true # do you **need** this mod to be able to launch?
# A version range using interval notation.
# Brackets mean "inclusive" bounds, while parentheses mean "exclusive".
versionRange = "[43,)" # This essentially means any forge >= @FORGE_LOADER_MAJOR@
ordering = "NONE" # Use this if you want your mod to be loaded specifically BEFORE or AFTER another mod
side = "BOTH" # Specify where this mod is required: can be BOTH, CLIENT or SERVER

# And another dependency, use this if you want to require a certain Minecraft version.
[[dependencies.minecraft_common]]
modId = "minecraft"
mandatory = true
# See above for how to read this notation, this essentially means any
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"