//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	implementation(project(":forgero-core-2"))

	// Fabric Loader
	modCompileOnly("net.fabricmc:fabric-loader:${project.loader_version}")

	// Fabric API
	modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")

	modApi("maven.modrinth:arrp:${project.advanced_runtime_resource_pack_version}")
}

loom {
	accessWidenerPath = file("src/main/resources/render.accesswidener")
}
