//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	api(project(":modules:core"))
	api(project(path: ":modules:mc:loader", configuration: 'namedElements'))
	api(project(path: ":modules:mc:common", configuration: 'namedElements'))

	// Fabric
	modCompileOnly("net.fabricmc:fabric-loader:${project.loader_version}")
	modCompileOnly("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")

	// Testing
	testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
	testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")
	modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")
	modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
	testImplementation("net.fabricmc:fabric-loader-junit:${project.loader_version}")

	// Content data required for Forgero initialization in tests
	testRuntimeOnly(project(":content:forgero-materials"))
	testRuntimeOnly(project(":content:minecraft-tools"))
	testRuntimeOnly(project(":content:forgero-base"))

	// Forgero test utilities
	testImplementation(project(":modules:mc:test-common"))
}

loom {
	runs {
		testServer {
			server()
			name = "Test Server"
			source sourceSets.test
		}
		gameTest {
			inherit testServer
			name "Game Test"
			vmArg "-Dfabric-api.gametest"
			runDir "build/gameTest"
		}
		testClient {
			client()
			name = "Test Client"
			vmArg "-Dfabric-api.gametest.structures.output-dir=${file("src/test/resources/data/forgero-blocks/gametest/structures")}"
			source sourceSets.test
		}
	}
}

sourceSets {
	test {
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath
	}
}

test {
	useJUnitPlatform()
	maxParallelForks = 32
	testLogging.events("failed")
	testLogging.info.events = ["failed", "skipped"]
}
