//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

subprojects {
    apply plugin: "fabric-loom"

    dependencies {
        minecraft "com.mojang:minecraft:$project.minecraft_version"
        mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    }
}

subprojects {
	processResources {
		inputs.property "version", project.version

		filesMatching("fabric.mod.json") {
			expand "version": project.version
		}
	}

	jar {
		from("LICENSE") {
			rename { "${it}_${base.archivesName.get()}" }
		}
	}
	java {
		withSourcesJar()
	}
}

subprojects {
	dependencies {
		implementation 'org.jetbrains:annotations:23.0.0'
		testImplementation 'org.junit.jupiter:junit-jupiter:5.9.0'
	}

	test {
		useJUnitPlatform()
	}

	java {
		withSourcesJar()
	}
}
