package com.sigmundgranaas.forgero.smithing.recipe.Custom;

import com.google.gson.JsonObject;
import com.sigmundgranaas.forgero.smithing.item.custom.CrucibleItem;
import net.minecraft.inventory.SimpleInventory;
import net.minecraft.item.ItemStack;
import net.minecraft.network.PacketByteBuf;
import net.minecraft.recipe.Ingredient;
import net.minecraft.recipe.Recipe;
import net.minecraft.recipe.RecipeSerializer;
import net.minecraft.recipe.RecipeType;
import net.minecraft.recipe.ShapedRecipe;
import net.minecraft.registry.DynamicRegistryManager;
import net.minecraft.util.Identifier;
import net.minecraft.util.JsonHelper;
import net.minecraft.world.World;

/**
 * Represents a recipe for molding liquid metal in a mold using a crucible.
 * This recipe is defined by a specific liquid, an amount, a mold, and a resulting item.
 *
 * @param id           The unique identifier for this recipe.
 * @param liquid       The identifier of the liquid required (e.g., "minecraft:lava", "forgero:molten_iron").
 * @param coolingTime  The time in ticks it takes for the item to "cool" and be crafted.
 * @param liquidAmount The amount of liquid required, measured in the crucible's internal units.
 * @param mold         The ingredient that represents the mold item.
 * @param result       The item stack produced upon a successful craft.
 */
public record MetalMoldRecipe(
		Identifier id,
		Identifier liquid,
		int coolingTime,
		int liquidAmount,
		Ingredient mold,
		ItemStack result
) implements Recipe<SimpleInventory> {

	// Constants for inventory slot indices to improve readability
	private static final int MOLD_SLOT = 0;
	private static final int CRUCIBLE_SLOT = 2;

	@Override
	public boolean matches(SimpleInventory inventory, World world) {
		if (inventory.size() < 3) {
			return false;
		}

		final ItemStack moldStack = inventory.getStack(MOLD_SLOT);
		final ItemStack crucibleStack = inventory.getStack(CRUCIBLE_SLOT);

		// 1. Check if the mold is correct.
		if (!this.mold.test(moldStack)) {
			return false;
		}

		// 2. Check if the second item is a valid CrucibleItem.
		if (!(crucibleStack.getItem() instanceof CrucibleItem crucibleItem)) {
			return false;
		}

		// 3. Check if the crucible contains the correct liquid type.
		Identifier crucibleLiquid = crucibleItem.getLiquidType(crucibleStack);
		if (crucibleLiquid == null || !crucibleLiquid.equals(this.liquid)) {
			return false;
		}

		// 4. Check if the crucible has enough liquid.
		return crucibleItem.hasMoreOrEqualLiquid(crucibleStack, this.liquidAmount);
	}

	@Override
	public ItemStack craft(SimpleInventory inventory, DynamicRegistryManager registryManager) {
		return this.result.copy(); // Always return a copy
	}

	@Override
	public boolean fits(int width, int height) {
		// This type of recipe doesn't use the crafting grid, so this is always true.
		return true;
	}

	@Override
	public ItemStack getOutput(DynamicRegistryManager registryManager) {
		return this.result.copy();
	}

	@Override
	public Identifier getId() {
		return this.id;
	}

	@Override
	public RecipeSerializer<?> getSerializer() {
		return Serializer.INSTANCE;
	}

	@Override
	public RecipeType<?> getType() {
		return Type.INSTANCE;
	}

	// Public getters are implicitly generated by the record class.
	// e.g., recipe.liquid(), recipe.coolingTime(), etc.

	public static class Type implements RecipeType<MetalMoldRecipe> {
		public static final Type INSTANCE = new Type();
		// This is the ID that will be used in the recipe JSON file ("type": "forgero:metal_molding")
		public static final String ID = "metal_molding";

		private Type() { /* Private constructor to prevent instantiation */ }
	}

	public static class Serializer implements RecipeSerializer<MetalMoldRecipe> {
		public static final Serializer INSTANCE = new Serializer();
		// This ID must match the Type's ID and is used for registration.
		public static final String ID = "metal_molding";

		@Override
		public MetalMoldRecipe read(Identifier id, JsonObject json) {
			Identifier liquid = new Identifier(JsonHelper.getString(json, "liquid"));
			int coolingTime = JsonHelper.getInt(json, "cooling_time", 200); // Default 10 seconds (20 ticks/sec)
			int liquidAmount = JsonHelper.getInt(json, "liquid_amount");
			Ingredient mold = Ingredient.fromJson(JsonHelper.getObject(json, "mold"));
			ItemStack result = ShapedRecipe.outputFromJson(JsonHelper.getObject(json, "result"));

			return new MetalMoldRecipe(id, liquid, coolingTime, liquidAmount, mold, result);
		}

		@Override
		public MetalMoldRecipe read(Identifier id, PacketByteBuf buf) {
			Identifier liquid = buf.readIdentifier();
			int coolingTime = buf.readVarInt();
			int liquidAmount = buf.readVarInt();
			Ingredient mold = Ingredient.fromPacket(buf);
			ItemStack result = buf.readItemStack();

			return new MetalMoldRecipe(id, liquid, coolingTime, liquidAmount, mold, result);
		}

		@Override
		public void write(PacketByteBuf buf, MetalMoldRecipe recipe) {
			buf.writeIdentifier(recipe.liquid());
			buf.writeVarInt(recipe.coolingTime());
			buf.writeVarInt(recipe.liquidAmount());
			recipe.mold().write(buf);
			buf.writeItemStack(recipe.result());
		}
	}
}
