//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
	// Reach Entity Attributes
	modApi("com.jamieswhiteshirt:reach-entity-attributes:${project.reach_entity_attributes_version}") {
		exclude(group: "net.fabricmc.fabric-loader")
	}
}

loom {
	accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
}

test {
	useJUnitPlatform()
}
